<center> <h1> DS 3000 </h1> </center>
<center> <h1> Homework Assignment 6</h1> </center>

<center> <h3> Abby Carr </h3></center>

### What to do

* Carefully read the description below.
* **As you write your code, please include comments.**
* Make sure you execute your code for each question and **compare** the output to the sample output provided, if any.
* **Refrain** from using advanced Python capabilities that were not covered in class.
* **When in doubt, ASK!** Post a question on the Piazza discussion forum for this homework assignment.
* Complete the assignment on your own!

### What to submit
* When you are done with the assignment, save it.
* Download it as a **Jupyter Notebook** (DS3000_HW6.ipynb)
* Upload your downloaded Notebook to Google Colab (https://colab.research.google.com/notebooks/)
* Get a shareable link to your Notebook on Colab
    * Go to Share near the top-right corner of the screen.
    * **Make sure you select Anyone with the Link Can View**
    * Copy the link
* Go to Canvas.
* **Upload your Jupyter Notebook through the Canvas assignment link.**
* **Paste the link to you Colab Notebook in the Add Comments field.**
* You can submit multiple attempts. The last attempt will be graded.

<center> <h2> Part 1 </h2> </center>

In this assignment, you will work with another ML dataset: Energy Efficiency (for buildings). You will apply various regression estimators to the dataset to predict the overall energy efficiency of buildings from various building parameters.

The link to the dataset is provided below.

The variables of the dataset are as follows:
    * X1 Relative Compactness
    * X2 Surface Area
    * X3 Wall Area
    * X4 Roof Area
    * X5 Overall Height
    * X6 Orientation
    * X7 Glazing Area
    * X8 Glazing Area Distribution
    * y1 Heating Load
    * y2 Cooling Load

As you can see, there are two possible target variables in the dataset (y1 and y2). In this assignment, however, you will only work with the target variable of y2.

Hint: Visit https://archive.ics.uci.edu/ml/datasets/Energy+efficiency# to learn more about the dataset and its features.

In this part of the assignment, you will retrieve and prepare the dataset for regression analysis.

### Question 1 (1pt)

Write a function that retrieves the Energy Efficiency dataset from UCI Machine Learning Repository using the link below:
    * https://archive.ics.uci.edu/ml/machine-learning-databases/00242/ENB2012_data.xlsx
    
Your function should return a dataframe containing the features and target variables from this dataset as shown below:
    * Your dataframe should include 768 rows and 10 columns.

In [6]:
import pandas as pd
import urllib

def load_data(excel_link):
    return pd.read_excel(excel_link)

In [17]:
energy_df = load_data('https://archive.ics.uci.edu/ml/machine-learning-databases/00242/ENB2012_data.xlsx')

In [18]:
energy_df =

       X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0    0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1    0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2    0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3    0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4    0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28
..    ...    ...    ...     ...  ...  ..  ...  ..    ...    ...
763  0.64  784.0  343.0  220.50  3.5   5  0.4   5  17.88  21.40
764  0.62  808.5  367.5  220.50  3.5   2  0.4   5  16.54  16.88
765  0.62  808.5  367.5  220.50  3.5   3  0.4   5  16.44  17.11
766  0.62  808.5  367.5  220.50  3.5   4  0.4   5  16.48  16.61
767  0.62  808.5  367.5  220.50  3.5   5  0.4   5  16.64  16.03

[768 rows x 10 columns]

### Question 2 (1pt)

Write a one-line code snippet to drop the column Y1 from energy_df and also rename the column Y2 to a new name called 'target'.

In [19]:
energy_df = energy_df.drop("Y1",axis =1).rename(columns={"Y2":"target"})

In [20]:
energy_df

       X1     X2     X3      X4   X5  X6   X7  X8  target
0    0.98  514.5  294.0  110.25  7.0   2  0.0   0   21.33
1    0.98  514.5  294.0  110.25  7.0   3  0.0   0   21.33
2    0.98  514.5  294.0  110.25  7.0   4  0.0   0   21.33
3    0.98  514.5  294.0  110.25  7.0   5  0.0   0   21.33
4    0.90  563.5  318.5  122.50  7.0   2  0.0   0   28.28
..    ...    ...    ...     ...  ...  ..  ...  ..     ...
763  0.64  784.0  343.0  220.50  3.5   5  0.4   5   21.40
764  0.62  808.5  367.5  220.50  3.5   2  0.4   5   16.88
765  0.62  808.5  367.5  220.50  3.5   3  0.4   5   17.11
766  0.62  808.5  367.5  220.50  3.5   4  0.4   5   16.61
767  0.62  808.5  367.5  220.50  3.5   5  0.4   5   16.03

[768 rows x 9 columns]

### Question 3 (2pts)
Write a function that extracts and returns a tuple of features and target variables from the energy_df dataframe above. Features are all columns from 0 to 7, and the target is the target column.
    * The features variable should be a DataFrame object with 768 rows and 8 columns
    * The target variable should be Series object with 768 values

In [34]:
def features_and_target(df):
    """Returns columns 0 to 8 of a given dataframe and the column titled target."""
    # get columns 0 to 8
    f = df.iloc[:,0:8]
    # get target column
    t = df.loc[:,'target']
    return f, t

In [35]:
features, target = features_and_target(energy_df)

In [36]:
features

       X1     X2     X3      X4   X5  X6   X7  X8
0    0.98  514.5  294.0  110.25  7.0   2  0.0   0
1    0.98  514.5  294.0  110.25  7.0   3  0.0   0
2    0.98  514.5  294.0  110.25  7.0   4  0.0   0
3    0.98  514.5  294.0  110.25  7.0   5  0.0   0
4    0.90  563.5  318.5  122.50  7.0   2  0.0   0
..    ...    ...    ...     ...  ...  ..  ...  ..
763  0.64  784.0  343.0  220.50  3.5   5  0.4   5
764  0.62  808.5  367.5  220.50  3.5   2  0.4   5
765  0.62  808.5  367.5  220.50  3.5   3  0.4   5
766  0.62  808.5  367.5  220.50  3.5   4  0.4   5
767  0.62  808.5  367.5  220.50  3.5   5  0.4   5

[768 rows x 8 columns]

In [37]:
target

0      21.33
1      21.33
2      21.33
3      21.33
4      28.28
       ...
763    21.40
764    16.88
765    17.11
766    16.61
767    16.03
Name: target, Length: 768, dtype: float64

In [1]:
import pandas as pd

# read in the CSV file from github
df = pd.read_csv("https://raw.githubusercontent.com/abbycarr/MA-education-machine-learning/main/Database%20Compliling%20Files/education_dataset_new.csv")
# makes the dataframe numeric
def clean(data):
    cleaned = data.replace(",","",regex=True)
    cleaned = cleaned.replace("\$","",regex=True)
    cleaned = cleaned.replace(" ","",regex=True)
    cleaned = pd.to_numeric(cleaned)
    return cleaned

df = df.apply(clean)
# Drop the Males column the directly correlates to Females
df = df.drop("Males", axis=1)
# Transform 'Students' and 'Students Disciplined' to 'Students Disciplined (%)'
df["Students Disciplined (%)"] = df["Students Disciplined"] / df["Students"]

# Transform 'Students' and 'Tests Takers' to 'Tests Takers (%)'
df["Tests Takers (%)"] = df["Tests Takers"] / df["Students"]

# Drop 'Students', 'Students Disciplined', and 'Tests Takers'
df = df.drop("Students",axis = 1)
df = df.drop("Students Disciplined",axis = 1)
df = df.drop("Tests Takers",axis = 1)
# Drop the target column
features = df.drop("Attending Coll./Univ. (%)",axis=1)
target = df["Attending Coll./Univ. (%)"]

<center><h1> Part 2 </h1></center>

In this part, you will apply and evaluate multiple regression estimators (Linear Regression, Ridge, Lasso, kNN, and LinearSVR) to the Energy Efficiency dataset.

### Question 3 (2pts)
Write a function that splits the dataset into training and testing sets. The function should return the training and test splits as shown in the sample function call. Use random_state=3000 when splitting your dataset.

In [2]:
from sklearn.model_selection import train_test_split

def split_the_dataset():
    return train_test_split(features,target,random_state=3000)

In [3]:
X_train, X_test, y_train, y_test = split_the_dataset()

### Question 4 (2pts)
You will find it useful to define a dictionary containing these five regression estimators so you can apply them in an iteration statement. For this question, import the relevant methods from sci-kit learn and define the estimators dictionary, containing Linear Regression, Ridge, Lasso, kNN, and LinearSVR (with max_iter).

In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import LinearSVR

In [12]:
#answer goes here

estimators = {
    "Linear Regression":LinearRegression(),
    "Ridge":Ridge(),
    "Lasso":Lasso(),
    "k-Nearest Neighbor":KNeighborsRegressor()
    }

In [13]:
#note that your output may not display all these values, depending on your sklearn version. 
#Do not manuallly enter all these values
estimators.values()

dict_values([LinearRegression(), Ridge(), Lasso(), KNeighborsRegressor()])

### Question 5 (5pts)
Write a function that fits these regression estimators to the training data using a percentage-split approach. You should use an iteration statement to apply these regression estimators. R-squared values should be displayed for both training and test sets.

In [14]:
from sklearn.metrics import r2_score

def regressors_percentage_split():
    """Fits the above regression estimators to the training data using a percentage-split approach"""
    
    # iterate through the dictionary keys
    for it in estimators:
        # print key/regression estimator name
        print("\n",it,":",sep="")
        
        # fit the model for this estimator
        model = estimators[it].fit(X=X_train, y=y_train)


        # print the r2 results
        print("\tR-squared value for training set: ", r2_score(y_train, model.predict(X_train)))
        print("\tR-squared value for testing set: ", r2_score(y_test, model.predict(X_test)))

In [15]:
#if you get a ConvergenceWarning, ignore it.
regressors_percentage_split()

Linear Regression:
	R-squared value for training set:  0.7825810805927639
	R-squared value for testing set:  0.7177617965576474

Ridge:
	R-squared value for training set:  0.7756392997671994
	R-squared value for testing set:  0.7128834947910967

Lasso:
	R-squared value for training set:  0.7636646273421851
	R-squared value for testing set:  0.6952248436564645

k-Nearest Neighbor:
	R-squared value for training set:  0.587520167491709
	R-squared value for testing set:  0.21809189881393387

/Users/abbycarr/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=4.98662e-20): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,
/Users/abbycarr/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 16243.859122735425, tolerance: 12.227885589772727
  model = cd_fast.enet_coordinate_descent(

### Question 6 (6pts)

For this question, you will normalize the X_train and X_test variables and perform the same multiple model fitting/evaluation that you did in the previous question. The output of this question will be similar to that of the previous question, with only one major distinction: here the normalized variables will be used to train and test the algorithms. For normalization, apply **MinMaxScaler()**.

Write a function that first applies the MinMaxScaler to the X_train and X_test global variables (as defined above) and then applies the same regression estimators. This function should also return the scaled variables, X_train_scaled and X_test_scaled respectively. You will need these variables in the next question.

In [16]:
from sklearn.preprocessing import MinMaxScaler

def preprocessed_regression():
    """Normalize the X_train and X_test variables above and then fits the above regression 
    estimators to that training data using a percentage-split approach"""

    # create and fit the scaler
    scaler = MinMaxScaler()
    scaler.fit(X_train) 
    
    # transforming the X data
    X_train_scaled = scaler.transform(X_train) 
    X_test_scaled = scaler.transform(X_test) 
    
    # iterate through the dictionary keys
    for it in estimators:
        # print key/regression estimator name
        print("\n",it,":",sep="")
        
        # fit the model for this estimator
        model = estimators[it].fit(X=X_train_scaled, y=y_train)

        # print the r2 results
        print("\tR-squared value for training set: ", r2_score(y_train, model.predict(X_train_scaled)))
        print("\tR-squared value for testing set: ", r2_score(y_test, model.predict(X_test_scaled)))
    
    
    return X_train_scaled, X_test_scaled

In [17]:
X_train_scaled, X_test_scaled = preprocessed_regression()

Linear Regression:
	R-squared value for training set:  0.7825810805927638
	R-squared value for testing set:  0.7177617970911214

Ridge:
	R-squared value for training set:  0.7696199721428011
	R-squared value for testing set:  0.726748794428627

Lasso:
	R-squared value for training set:  0.4157985516700977
	R-squared value for testing set:  0.42345706149686

k-Nearest Neighbor:
	R-squared value for training set:  0.861920631526666
	R-squared value for testing set:  0.7738601211231837

### Question 7 (6pts)
Looking at the previous output, it can be said that the kNN algorithm seems to works best for this dataset. In this question, you will attempt to improve the prediction performance by automatically selecting the most important features (k=3). 

Use recursive feature elimination (RFE) to select the **three** most important features. For your RFE, use a decision tree regressor to recursively eliminate the features. Your selection must be based on the X_train_scaled and X_test_scaled variables defined in the previous question. 

The idea is to use the scaled values that provided better results than raw values and to see if we can further improve the prediction performance by only using the most important features. Your function should produce the sample output given below and should also return the selected features, X_train_selected and X_test_selected.

In [30]:
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeRegressor

def RFE_feature_selection():
    """Uses recursive feature elimination (RFE) to select the three most important features of the above
    data and fits the data to the kNN regression estimator."""
    
    # create the RFE and fit it to the scaled data
    select = RFE(DecisionTreeRegressor(random_state = 3000),n_features_to_select = 10)
    select.fit(X_train_scaled, y_train)

    # transforming the X data
    X_train_selected = select.transform(X_train_scaled)
    X_test_selected = select.transform(X_test_scaled)

    # fit the kNN model with the transformed data
    model = KNeighborsRegressor().fit(X=X_train_selected, y=y_train)
    
    # print the selected 3 features
    print("Selected features after RFE:")
    for i in range(len(select.get_support())):
        if select.get_support()[i]:
            print("\t",features.columns[i],sep="")

    # print the kNN performance data
    print("\nkNN Regression performance with selected features:")
    print("\tR-squared value for training set: ", r2_score(y_train, model.predict(X_train_selected)))
    print("\tR-squared value for testing set: ", r2_score(y_test, model.predict(X_test_selected)))
    
    return X_train_selected, X_test_selected

In [31]:
X_train_selected, X_test_selected = RFE_feature_selection()

Selected features after RFE:
	Asian
	White
	Females
	Students With Disabilities %
	High Needs %
	Total Expenditures
	Total Expenditures per Pupil
	% Score 3-5
	Students Disciplined (%)
	Tests Takers (%)

kNN Regression performance with selected features:
	R-squared value for training set:  0.8629862188601701
	R-squared value for testing set:  0.7461786720383687

### Question 8 (5pts)

In this last question, you will perform a Grid Search to tune two key parameters of the kNN regression algorithm at the same time and determine which combination yields the best performance. Specifically, you will change the number of neighbors, **n_neighbors**, and the distance function used to calculate the distance between different data points, **metric**. The possible values for each hyperparameter are as follows:
    * For n_neighbors, try 1, 5, and 10.
    * For metric, try ""euclidean", "manhattan", and "minkowski".

You can learn more about these three distance functions at https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.DistanceMetric.html.


Write a function that applies a Grid Search with kNN regression estimator and evaluates the performance of these parameters using 5-fold evaluation. Your function should produce the provided output. Your function should use the X_train_selected and X_test_selected variables.

In [32]:
from sklearn.model_selection import GridSearchCV

def grid_search_kNN():
    """Performs a grid search to fine tune the n_neighbors and metric of the above kNN model."""
    
    # perform and fit the above grid search
    grid_search = GridSearchCV(KNeighborsRegressor(),{"n_neighbors":[1,5,10],"metric":["euclidean", "manhattan", "minkowski"]},cv=5)
    grid_search.fit(X=X_train_selected, y=y_train)
    
    # outputs results
    print("Best parameters: ", grid_search.best_params_)
    print("Training set score with best parameters: ", grid_search.score(X_train_selected, y_train))
    print("Test set score with best parameters: ", grid_search.score(X_test_selected, y_test))

In [33]:
grid_search_kNN()

Best parameters:  {'metric': 'manhattan', 'n_neighbors': 5}
Training set score with best parameters:  0.8723677819405401
Test set score with best parameters:  0.7592193542582304